Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

**Q1.** Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables

In [2]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [6]:
import numpy as np

In [23]:
list_.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [10]:
type(list_)

list

In [24]:
array_list=np.array(object=list_)

In [25]:
array_list=np.array(list_)

In [26]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [27]:
type(array_list)

numpy.ndarray

In [28]:
array_list.dtype

dtype('<U1')

**Q2.** Write a code to print the data type of each and every element of both the variables list_ and 
arra_list

In [18]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [29]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Q3**. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

In [32]:
array_list=np.array(object=list_,dtype=int)

In [35]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


yes there will be differnce in data type of elements as array_list has int data but list_ has element of string data type.

In [38]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [39]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

**Q4**. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [42]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [44]:
num_array.shape

(2, 3)

In [45]:
num_array.size

6

**Q5**.  Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

In [46]:
import numpy as np

In [47]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.matrix(np.zeros((3,3)))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

**Q6.** Create an identity matrix of shape (5,5) using numpy functions?

In [49]:
import numpy as np

In [51]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
np.matrix(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])